CREATE TABLE IF NOT EXISTS user_sessions (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    token TEXT NOT NULL,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE
);
CREATE INDEX IF NOT EXISTS idx_id ON users (id);