CREATE TYPE role AS ENUM ('USER', 'ADMIN');

CREATE TABLE IF NOT EXISTS users (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_uuid UUID,
    username VARCHAR(64),
    password VARCHAR(64),
    role VARCHAR(8) DEFAULT 'USER'
);
CREATE INDEX IF NOT EXISTS idx_id ON users (id);